name: .NET

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true'
    - name: Python Run
      run: python printenv.py
      env:
        TST_VAR: y
    - name: DotNet Run
      run: dotnet run --project printenv
      env:
        TST_VAR: y
